#//{
#//  "AWSEBDockerrunVersion": 2,
#//  "containerDefinitions": [
#//    {
#//      "name": "client",
#//      "image": "ryanbraving/multi-client",
#//      "hostname": "client",
#//      "essential": false
#//    },
#//    {
#//      "name": "server",
#//      "image": "ryanbraving/multi-server",
#//      "hostname": "api",
#//      "essential": false
#//    },
#//    {
#//      "name": "worker",
#//      "image": "ryanbraving/multi-worker",
#//      "hostname": "worker",
#//      "essential": false
#//    },
#//    {
#//      "name": "nginx",
#//      "image": "ryanbraving/multi-nginx",
#//      "hostname": "nginx",
#//      "essential": true,
#//      "portMappings": [
#//        {
#//          "hostPort": 80,
#//          "containerPort": 80
#//        }
#//      ],
#//      "links": ["client", "server"]
#//    }
#//  ]
#//}

version: "3"
services:
  client:
    image: "ryanbraving/multi-client"
#    mem_limit: 128m
    hostname: client
  server:
    image: "ryanbraving/multi-server"
#    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "ryanbraving/multi-worker"
#    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "ryanbraving/multi-nginx"
#    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"